[project]
name = "sekai-core"
version = "0.1.0"
description = "Core engine for SekaiTranslatorV"
authors = [{ name = "Satonix" }]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
